server:
  port: 8088

spring:
  application:
    name: bank-transfer-bank1

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bank1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root

dubbo:
  scan:
    base-packages: com.edward.banktransferbank1
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  application:
    qosEnable: true
    qosPort: 22222
    qosAcceptForeignIp: true
    qos-enable-compatible: true
    qos-host-compatible: localhost
    qos-port-compatible: 22222
    qos-accept-foreign-ip-compatible: true
    qos-host: localhost

#logging:
#  level:
#    root: error
#    org.springframework.web: info
#    org.apache.ibatis: debug
#    org.dromara.hmily.tac: debug
#    org.dromara.hmily.demo.bonuspoint: debug
#    org.dromara.hmily.demo.lottery: debug
#    org.dromara.hmily.demo: debug
#    io.netty: info
#  file:
#    path: "./logs"

org:
  dromara:
    hmily:
      hmily-zookeeper-config:
        host: localhost:2181
      hmily-db-config:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/hmily?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
      hmily-file-config:
        prefix: /hmily
        path: D:\\hmilyLog

