server:
  port: 8088

spring:
  application:
    name: bank-transfer-bank1

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bank1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root

dubbo:
  scan:
    base-packages: com.edward.banktransferbank1
  protocol:
    name: dubbo
    port: 12345
  application:
    qosEnable: true
    qosPort: 22222
    qosAcceptForeignIp: true
    qos-enable-compatible: true
    qos-host-compatible: localhost
    qos-port-compatible: 22222
    qos-accept-foreign-ip-compatible: true
    qos-host: localhost

